# Generated by Django 4.1.2 on 2022-10-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(default='', max_length=100)),
                ('custPhoneNumber', models.CharField(default='', max_length=11)),
                ('custEmail', models.CharField(default='', max_length=100)),
                ('custPassword', models.CharField(default='', max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField()),
                ('lastLoginDate', models.DateTimeField()),
                ('stat', models.CharField(default='A', max_length=1)),
            ],
        ),
    ]
