# Generated by Django 4.1.2 on 2022-10-10 13:35

import customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_initial'),
        ('customer', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(default='', max_length=100)),
                ('custPhoneNumber', models.CharField(default='', max_length=11)),
                ('custEmail', models.CharField(default='', max_length=100)),
                ('custPassword', models.CharField(default='', max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField()),
                ('lastLoginDate', models.DateTimeField()),
                ('stat', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(default='N', max_length=20)),
                ('orderTotal', models.IntegerField(default='0')),
                ('orderPaid', models.CharField(default='N', max_length=1)),
                ('orderSent', models.CharField(default='N', max_length=1)),
                ('orderRecept', models.CharField(default='N', max_length=1)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField()),
                ('stat', models.CharField(default='A', max_length=1)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderProduct', models.CharField(default='', max_length=20)),
                ('productQuantity', models.IntegerField(default='1')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField()),
                ('stat', models.CharField(default='A', max_length=1)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='customer.order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(default='', max_length=100)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to=customer.models.upload_des)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField()),
                ('stat', models.CharField(default='A', max_length=1)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagelip', to='customer.order')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrNameSent', models.CharField(default='', max_length=150)),
                ('addrDetail1', models.CharField(default='', max_length=150)),
                ('addrProvinceName', models.CharField(default='', max_length=100)),
                ('addrAmphoeName', models.CharField(default='', max_length=100)),
                ('addrTambolName', models.CharField(default='', max_length=100)),
                ('addrPostCode', models.CharField(default='', max_length=5)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField()),
                ('stat', models.CharField(default='A', max_length=1)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='customer.order')),
            ],
        ),
    ]
