# Generated by Django 4.1.2 on 2022-10-10 14:31

import customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(default='', max_length=100)),
                ('prodDetail', models.CharField(default='', max_length=250)),
                ('prodPrice', models.IntegerField(default='0')),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField()),
                ('stat', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='imageslip',
            name='imgUrl',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_des),
        ),
        migrations.AlterField(
            model_name='imageslip',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageslip', to='customer.order'),
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(default='', max_length=100)),
                ('imgUrl', models.ImageField(blank=True, null=True, upload_to=customer.models.upload_des)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField()),
                ('stat', models.CharField(default='A', max_length=1)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customer.product')),
            ],
        ),
    ]
