# Generated by Django 4.1.2 on 2022-10-10 15:18

import customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_product_alter_imageslip_imgurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslip',
            name='imgUrl',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_des),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product'),
        ),
    ]
