# Generated by Django 4.1.2 on 2022-10-22 13:56

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_imageslip_imgurl_alter_order_ordername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslip',
            name='imgUrl',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_des),
        ),
    ]
