# Generated by Django 4.1.2 on 2022-10-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0002_amphoe_tambol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amphoe',
        ),
        migrations.DeleteModel(
            name='Tambol',
        ),
    ]
