# Generated by Django 4.1.2 on 2022-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0005_tambol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tambol',
            name='postCode',
            field=models.IntegerField(default='0'),
        ),
    ]
