# Generated by Django 4.1.2 on 2022-10-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0006_tambol_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zCode', models.IntegerField(default='0')),
                ('zName', models.CharField(default='', max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField()),
            ],
        ),
    ]
