# Generated by Django 4.1.2 on 2022-10-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_imageslip_imgurl_alter_order_ordername_and_more'),
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
